name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)
trigger:
- master
- releases/*

resources:
- repo: self

queue:
  name: Hosted VS2017

variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2

  displayName: 'dotnet restore'

  inputs:
    command: restore

    projects: '**/*.csproj'

- task: Npm@1

  displayName: 'npm install'

  inputs:
    workingDir: $(Build.Repository.Name)/ClientApp
    verbose: false

- task: DotNetCoreCLI@2

  displayName: 'dotnet build'

  inputs:
    projects: '**/*.csproj'

    arguments: '--configuration $(BuildConfiguration)'

- task: mattlabrum.build-task.custom-build-task.downloadsSecureFile@0

  displayName: 'Download Secure File 27efdf69-4ae9-48a5-82d6-dde14d86aef0'

  inputs:
    fileInput: '27efdf69-4ae9-48a5-82d6-dde14d86aef0'

    targetPath: $(Build.Repository.Name)

- task: DotNetCoreCLI@2

  displayName: 'dotnet test'

  inputs:
    command: test

    projects: '**/$(Build.Repository.Name).Tests/*.csproj'

    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2

  displayName: 'dotnet publish'

  inputs:
    command: publish

    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1

  displayName: 'Publish Artifact: drop'

  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
