name: $(System.TeamProject)_$(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)

variables:
  BuildConfiguration: 'Release'
  RepoName: 'Songhay.Blog'

trigger:
  batch: false
  branches:
    include:
    - master
    - releases/*
  paths:
    exclude:
    - Songhay.Blog.Repository.Tests/*
    - Songhay.Blog.Shell.Tests/*
    - Songhay.Blog.Tests/*

#TODO: wait for “macro support” for exclude
#[https://github.com/Microsoft/azure-pipelines-tasks/issues/9235#issuecomment-451982478]

resources:
- repo: self

queue:
  name: Hosted VS2017

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: $(RepoName)/ClientApp
    verbose: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: mattlabrum.build-task.custom-build-task.downloadsSecureFile@0
  displayName: 'Download Secure File 27efdf69-4ae9-48a5-82d6-dde14d86aef0'
  inputs:
    fileInput: '27efdf69-4ae9-48a5-82d6-dde14d86aef0'
    targetPath: $(RepoName)

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/$(RepoName).Tests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
